# Generated by Django 5.2.1 on 2025-07-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastion_app', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='country_code',
            field=models.CharField(default='880', max_length=10),
            preserve_default=False,
        ),
    ]
