# Generated by Django 5.2.1 on 2025-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastion_app', '0004_alter_cartitem_price_alter_cartitem_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='grand_total',
            new_name='combined_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_details',
            new_name='ordered_products',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('bKash', 'bKash'), ('Nagad', 'Nagad'), ('COD', 'Cash on Delivery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
