# Generated by Django 5.2.1 on 2025-07-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastion_app', '0005_rename_grand_total_order_combined_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
